#!/bin/sh

choose=$(printf "dirs\\nall" | dmenu -i -p "Only directories or all?")
case "$choose" in
	"dirs")
		text=$(tree -d -i -f $HOME | dmenu -i -l 20 -p "Choose dir path to save to clipboard")
		echo $text | xclip -selection clipboard
		echo $text | xclip
	;;
	"all")
		text=$(tree -i -f $HOME | dmenu -i -l 20 -p "Choose dir path to save to clipboard")
		echo $text | xclip -selection clipboard
		echo $text | xclip
	;;
esac

