#!/usr/bin/env bash
scrot /tmp/screen.png
convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png
ICON=$HOME/.scripts/files/lock.png
if [ ! -e $ICON ]; then
	[[ -f $1 ]] && convert /tmp/screen.png $1 -gravity center -composite -matte /tmp/screen.png
else
	convert /tmp/screen.png /home/havra/.scripts/files/lock.png -gravity NorthWest -composite -matte /tmp/screen.png
fi
mpc pause
i3lock -i /tmp/screen.png
rm /tmp/screen.png
