#!/bin/sh
choose=$(printf "laptop\\nexternal\\ndual\\nmanual" | rofi -dmenu -i -p "Choose monitor setup")

case "$choose" in
	"laptop")
		xrandr --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --off --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output DP-2 --off
		sleep 1
		setbg
		remap.sh
		;;
	"external")
		xrandr --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --mode 2560x1080 --pos 0x0 --rotate normal --output eDP-1 --off --output DP-2 --off
		sleep 1
		setbg
		remap.sh
		;;
	"dual")
		xrandr --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output eDP-1 --mode 1366x768 --pos 2560x432 --rotate normal --output DP-2 --off
		sleep 1
		setbg
		remap.sh
		;;
	"manual")
		arandr
		sleep 1
		setbg
		remap.sh
		;;
esac
