#!/bin/sh

TOGGLE=/tmp/.toggleGaps

if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
    i3-msg gaps inner all set 0
    i3-msg gaps outer all set 0
else
    rm $TOGGLE
    i3-msg gaps inner all set 10
    i3-msg gaps outer all set -3
fi
