#!/bin/sh
while read file
do
	case "$1" in
		"w") setbg "$file" & ;;
		"r")
			convert -rotate 90 "$file" "$file" ;;
		"R")
			convert -rotate -90 "$file" "$file" ;;
		"f")
			dragon-drop --and-exit "$file" & ;;
		"p")
		setsid -f pinta "$file" >/dev/null 2>&1 & ;;
		"g")
		setsid -f gimp "$file" >/dev/null 2>&1 & ;;
		"y")
			echo -n "$file" | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" & ;;
		"Y")
			echo -n "$(readlink -f "$file")" | xclip -selection clipboard &&
				notify-send "$(readlink -f "$file") copied to clipboard" & ;;
		"d")
			[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;

	esac
done
