#!/usr/bin/bash
# toggles dropdown terminal, window will always be centered

if [ -z $1 ]; then
	echo "Usage: $0 <name of hidden scratchpad window>"
	exit 1
fi

pids=$(xdotool search --class ${1})
for pid in $pids; do
	echo "Toggle $pid"
	width=$(($(xdotool getwindowgeometry --shell $pid | grep WIDTH | awk -F "=" '{print $2}')/2))
	height=$(($(xdotool getwindowgeometry --shell $pid | grep HEIGHT | awk -F "=" '{print $2}')/2))
	xdotool windowmove $pid 50% 50%
	xdotool windowmove --relative $pid -$width -$height
	bspc node $pid --flag hidden -f
done
