#!/bin/bash

# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# URLs will be directly handed to the browser.
# Anything else, it search it.
browser=${BROWSER:-firefox}

pgrep -x dmenu && exit

choice=$(echo "	 	" | rofi -dmenu -i -p "Search DuckDuckGo:") || exit 1

if [ "$choice" = "	 	"  ]; then
    $browser "https://duckduckgo.com"
	i3-msg workspace 1
else
    # Detect if url
    if [[ "$choice" =~ ^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$ ]]; then
        $browser "$choice"
		i3-msg workspace 1
    else
        $browser "https://duckduckgo.com/?q=$choice&t=ffab&atb=v1-1"
    	i3-msg workspace 1
	fi
fi
