#!/bin/sh
choose=$(printf "speed 1\\nspeed 2\\nspeed 3\\nspeed 4\\nspeed 5\\nspeed auto" | rofi -dmenu -i -p "Choose fan speed")

pass=$(echo "" | rofi -dmenu -config $HOME/.config/rofi/colorLess.rasi -i -p "Enter sudo password")
if [ "$pass" != "" ]; then
	case "$choose" in
		"speed 1")
			echo $pass | echo level 1| sudo tee /proc/acpi/ibm/fan
			;;
		"speed 2")
			echo $pass | echo level 2| sudo tee /proc/acpi/ibm/fan
			;;
		"speed 3")
			echo $pass | echo level 3| sudo tee /proc/acpi/ibm/fan
			;;
		"speed 4")
			echo $pass | echo level 4| sudo tee /proc/acpi/ibm/fan
			;;
		"speed 5")
			echo $pass | echo level 5| sudo tee /proc/acpi/ibm/fan
			;;
		"speed auto")
			echo $pass | echo level auto| sudo tee /proc/acpi/ibm/fan
			;;
	esac
fi
