#!/bin/sh
choose=$(printf "speed 1\\nspeed 2\\nspeed 3\\nspeed 4\\nspeed 5\\nspeed auto" | rofi -dmenu -i -p "Choose fan speed")

case "$choose" in
	"speed 1")
		sudo echo level 1| sudo tee /proc/acpi/ibm/fan
		;;
	"speed 2")
		sudo echo level 2| sudo tee /proc/acpi/ibm/fan
		;;
	"speed 3")
		sudo echo level 3| sudo tee /proc/acpi/ibm/fan
		;;
	"speed 4")
		sudo echo level 4| sudo tee /proc/acpi/ibm/fan
		;;
	"speed 5")
		sudo echo level 5| sudo tee /proc/acpi/ibm/fan
		;;
	"speed auto")
		sudo echo level auto| sudo tee /proc/acpi/ibm/fan
		;;
esac
