#!/bin/sh
# Gives a rofi -dmenu prompt to mount unmounted drives.
# If they're in /etc/fstab, they'll be mounted automatically.
# Otherwise, you'll be prompted to give a mountpoint from already existsing directories.
# If you input a novel directory, it will prompt you to create that directory.


mountusb() { \
	chosen="$(echo "$usbdrives" | rofi -dmenu -i -p "Mount which drive?" | awk '{print $1}')"
	sudo -A mount "$chosen" && notify-send "💻 USB mounting" "$chosen mounted." && exit 0
	partitiontype="$(lsblk -no "fstype" "$chosen")"
	case "$partitiontype" in
		"vfat") udisksctl mount -t vfat -b "$chosen" && notify-send "💻 USB mounting" "Mounted to. /usr/bin/media" ;;
		*) udisksctl mount -b "$chosen" && notify-send "💻 USB mounting" "Mounted to. /usr/bin/media";;
	esac
	}

mountandroid() { \
	chosen=$(echo "$anddrives" | rofi -dmenu -i -p "Which Android device?" | cut -d : -f 1)
	simple-mtpfs --device "$chosen" $HOME/Mount
	notify-send "🤖 Android Mounting" "Android device mounted to ~/Android."
	}

asktype() { \
	case $(printf "USB\\nAndroid" | rofi -dmenu -i -p "Mount a USB drive or Android device?") in
		USB) mountusb ;;
		Android) mountandroid ;;
	esac
	}

anddrives=$(simple-mtpfs -l 2>/dev/null)
usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usbdrives" ]; then
	[ -z "$anddrives" ] && echo "No USB drive or Android device detected" && notify-send "No USB drive or Android device detected" && exit
	echo "Android device(s) detected."
	mountandroid
else
	if [ -z "$anddrives" ]; then
		echo "USB drive(s) detected."
	       	mountusb
	else
		echo "Mountable USB drive(s) and Android device(s) detected."
		asktype
	fi
fi
