#!/bin/bash
bspc rule -r "*"

# Rules
bspc rule -a Zathura state=tiled
bspc rule -a gpt sticky=on state=floating hidden=on rectangle=800x600+0+0

# Autostart
setbg &
xrdb .Xresources
rsw &


# Global Settings
bspc config automatic_scheme longest_side
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config pointer_follows_focus false

bspc config single_monocle false
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#121212"
bspc config active_border_color	"#ffffd7"
bspc config focused_border_color "#ffffd7"
bspc config presel_feedback_color	"#121212"
bspc config urgent_border_color "#dd2727"

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 20
bspc config border_width 2
bspc config window_gap 4


if [ ! -f /tmp/bspwm_starup ] ; then
	screen-chooser laptop &
	touch /tmp/bspwm_startup
fi

