#!/bin/sh
bspc rule -r "*"

###---Autostart---###
setbg &
xrdb .Xresources &
polybarLaunch &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
remap.sh &
sudo light -S 21 &
pactl set-sink-volume @DEFAULT_SINK@ 50% &
mpc volume 100 &
pactl set-source-mute @DEFAULT_SOURCE@ 1 &
xinput set-prop 12 166 0 &

###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

###---Global Settings---###
bspc config automatic_scheme longest_side

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
bspc config pointer_follows_focus false

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"458588"
bspc config active_border_color	"#c6c8c5"
bspc config focused_border_color "#c6c8c5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 23
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 0


###---Rules---###
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a gpt sticky=on state=floating hidden=on rectangle=800x600+0+0
bspc rule -a rss sticky=on state=floating hidden=on rectangle=1200x650+0+0
bspc rule -a notes sticky=on state=floating hidden=on rectangle=800x700+0+0
bspc rule -a math sticky=on state=floating hidden=on rectangle=800x300+0+0

reloadScratchpadWindows
