#!/bin/sh
bspc rule -r "*"

###---Autostart---###
setbg &
xrdb .Xresources &
polybarLaunch &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
remap.sh &
sudo light -S 21 &
pactl set-sink-volume @DEFAULT_SINK@ 50% &
mpc volume 100 &
pactl set-source-mute @DEFAULT_SOURCE@ 1 &
xinput set-prop 12 166 0 &


###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
